PATH=$HOME/bin:$PATH
PATH=$HOME/system/bin:$PATH
LD_LIBRARY_PATH=$HOME/system/lib
LD_LIBRARY_PATH=$HOME/system/lib32:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=$HOME/system/lib64:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=$HOME/system/winelib:$LD_LIBRARY_PATH
LD_LIBRARY_PATH=$HOME/system/winelib32:$LD_LIBRARY_PATH

export PATH
export LD_LIBRARY_PATH
