#! /bin/sh

bspc config border_width        3
bspc config window_gap          6 
bspc config normal_border_color     "#1c1c1c"
bspc config focused_border_color    "#1c1c1c"

bspc config top_padding        24

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d "Workspace 1" "Workspace 2" "Workspace 3" "Workspace 4"

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sxhkd -c /home/marvin/.config/sxhkd/sxhkdrc_bspwm
