#! /bin/sh

bspc config border_width        3
bspc config window_gap          8
bspc config normal_border_color     "#4d4d4d"
bspc config focused_border_color    "#b3b3b3"
bspc config presel_feedback_color   "#959595"

bspc config top_padding        24

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d "Workspace 1" "Workspace 2" "Workspace 3" "Workspace 4" "Workspace 5"

bspc rule -a floating state=floating

sxhkd -c $HOME/.config/sxhkd/sxhkdrc_bspwm
