#!/usr/bin/env bash

bspc config border_width        4
bspc config window_gap          0

bspc config top_padding         22
bspc config bottom_padding      0
bspc config left_padding        0
bspc config right_padding       0

bspc config normal_border_color     "#4d4d4d"
bspc config focused_border_color    "#b3b3b3"
bspc config presel_feedback_color   "#404345"

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config click_to_focus      true
bspc config pointer_modifier    mod1
bspc config pointer_action1     move
bspc config pointer_action2     none
bspc config pointer_action3     resize_side

bspc monitor -d terminal terminal web web stuff stuff garbage garbage music chat

bspc rule -a floating state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Pqiv border=off

sxhkd -c ${HOME}/.config/sxhkd/sxhkdrc_bspwm &
polybar main-bspwm &
